### ISSUE TITLE
Clockpicker - reversing pick

### ISSUE THREAD

**Issue by boRp** [boRp/diabetes-diary#1]
[Android] When a user chooses to edit the time of a new data point, and then confirms, the selection can not be reversed. Upon (the second) tap onto the time, only the dialogue to change the minutes will open - the hour can not be changed. Not an issue in browser (chromium).

**Comment by psturm** [comment]
Seems, the problem is caused by `onfocus="blur();` (which is used to hide the softkeyboard on mobile)

For now, we just show the default title bar of the clockpicker again, which will allow to select between hours/minutes
